Repository JoshMallery/BranchOut, pull requests merged in 2022-06, with the labels that each got.

#10 Feature/build lesson components/wp
  public/index.html
  src/CSS/CourseContainer.css
  src/CSS/CourseContent.css
  src/CSS/LessonCard.css
  src/CSS/Lessons.css
  src/apiCalls/apiCalls.js
  src/components/CourseContainer.js
  src/components/CourseContent.js
  src/components/LessonCard.js
  src/components/Lessons.js
Labels: MVP

#11 Apply basic styling to course view
  src/CSS/App.css
  src/CSS/CourseContainer.css
  src/CSS/CourseContent.css
  src/CSS/Dashboard.css
  src/CSS/LessonCard.css
  src/CSS/Lessons.css
  src/components/CourseContainer.js
  src/components/CourseContent.js
Labels: enhancement

#18 Styling/form styling
  src/App.js
  src/CSS/CourseCard.css
  src/CSS/Form.css
  src/apiCalls/apiCalls.js
  src/components/CourseContainer.js
  src/components/Dashboard.js
  src/components/Form.js
  src/components/Lessons.js
  src/images/red-hand.png
  src/images/trash-icon.png
Labels: enhancement, MVP

#19 Feature/testing
  cypress.config.js
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/branchOut/dashboard.cy.js
  cypress/fixtures/courses.json
  cypress/fixtures/example.json
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: enhancement

#25 Feature/dashboard test
  cypress/e2e/branchOut/courseContent.cy.js
  cypress/e2e/branchOut/dashboard.cy.js
  cypress/e2e/branchOut/form.cy.js
  src/CSS/CourseCard.css
  src/components/Dashboard.js
Labels: MVP

#27 Feature/error handling
  cypress/e2e/branchOut/dashboard.cy.js
  src/App.js
  src/apiCalls/apiCalls.js
  src/components/CourseContainer.js
Labels: enhancement

#29 Refactor mvp
  cypress/e2e/1-getting-started/todo.cy.js
  cypress/e2e/2-advanced-examples/actions.cy.js
  cypress/e2e/2-advanced-examples/aliasing.cy.js
  cypress/e2e/2-advanced-examples/assertions.cy.js
  cypress/e2e/2-advanced-examples/connectors.cy.js
  cypress/e2e/2-advanced-examples/cookies.cy.js
  cypress/e2e/2-advanced-examples/cypress_api.cy.js
  cypress/e2e/2-advanced-examples/files.cy.js
  cypress/e2e/2-advanced-examples/local_storage.cy.js
  cypress/e2e/2-advanced-examples/location.cy.js
  cypress/e2e/2-advanced-examples/misc.cy.js
  cypress/e2e/2-advanced-examples/navigation.cy.js
  cypress/e2e/2-advanced-examples/network_requests.cy.js
  cypress/e2e/2-advanced-examples/querying.cy.js
  cypress/e2e/2-advanced-examples/spies_stubs_clocks.cy.js
  cypress/e2e/2-advanced-examples/traversal.cy.js
  cypress/e2e/2-advanced-examples/utilities.cy.js
  cypress/e2e/2-advanced-examples/viewport.cy.js
  cypress/e2e/2-advanced-examples/waiting.cy.js
  cypress/e2e/2-advanced-examples/window.cy.js
  cypress/e2e/branchOut/courseContent.cy.js
  cypress/fixtures/example.json
  src/CSS/CourseCard.css
  src/CSS/Dashboard.css
  src/CSS/Form.css
  src/CSS/LessonCard.css
  src/CSS/Lessons.css
  src/CSS/NavBar.css
  src/apiCalls/apiCalls.js
  src/components/CourseContainer.js
  src/components/Dashboard.js
  src/components/DropDown.js
  src/components/Form.js
  src/components/Lessons.js
  src/components/NavBar.js
Labels: MVP

#32 Styling/form error msg
  src/CSS/Form.css
  src/components/CourseContainer.js
  src/components/CourseContent.js
  src/components/Dashboard.js
  src/components/Form.js
  src/components/NavBar.js
  src/index.js
Labels: MVP
